# Copyright (c) 2026 Joshua Seaton
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

[toolchain]
channel = "nightly-2026-05-01"
components = [
    "llvm-tools", # For cargo-binutils
    "rust-analyzer",
    "rust-src", # For -Z build-std
]
