# Copyright (c) 2026 Joshua Seaton
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

platform = "qemu-virt-riscv"
boot_flash_address = 0x2000_0000
boot_flash_size = 0x200_0000

# For size discipline, we constrain the available boot RAM to 64KiB.
boot_ram_address = 0x8000_0000
boot_ram_size = 0x1_0000

[qemu]
boot_medium = "pflash"
cpu = "rv32,h=false,s=false"
flash_size = "32M"
machine = "virt"
memory = "64K"
